# External Gems
gems: 						[jekyll-paginate]
exclude: [node_modules, gulpfile.js]


# Site Settings
title: 						"Garin.IO"
email: 						"itay.garin@gmail.com"
description: 			"Your Guide to a World Full of Bits"
baseurl: 					""
logourl: 					"/assets/img/author.jpg"
fa-logo: 					"fa-bookmark-o"
paginate: 				5


# Author Settings
author_name: 				"Itay Garin"
author_url: 				"http://garin.io"
author_bio: 				"Itay is a developer and a researcher who's passionate about solving low-level challenges.
He loves to tinker with electronics, to optimize his Emacs config, and to learn new technologies."
author_email: 			"itay.garin@gmail.com"
author_image: 			"/assets/img/author.jpg"


# Social Settings
twitter_url: 				"https://twitter.com/ItayGarin"
facebook_url: 			""
github_url:  				"https://github.com/ItayGarin"
youtube_url:  			""
dribbble_url:  			""
googleplus_url: 		""
instagram_url:  		""
pinterest_url:  		""
linkedin_url:  			"https://linkedin.com/in/itay-garin-4307658b"


# Theme Settings
theme_disqus_shortname: 	"garinio"
theme_google_comments: 		false
theme_analytics_id: 		  "UA-77135256-1"
theme_reading_time: 		  true
theme_autoload_comments: 	true
theme_always_show_nav: 		false


# SASS Settings
# DO NOT MODIFY
sass:
 sass_dir: "assets/css/"
 style: :compressed


# Build Settings
markdown: 					kramdown
permalink: 					pretty

kramdown:
  input: GFM
  syntax_highlighter: rouge
